name: Test Book Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-book:
    name: Build and Test mdBook
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install mdBook
        run: |
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.37/mdbook-v0.4.37-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          chmod +x mdbook
          sudo mv mdbook /usr/local/bin/
          mdbook --version
      
      - name: Build book
        run: mdbook build
      
      - name: Test book structure
        run: |
          echo "✅ Checking book built successfully..."
          test -f book/index.html
          test -f book/ch01-00-getting-started.html || true
          echo "✅ Book structure looks good!"
      
      - name: Check for broken internal links
        run: |
          echo "🔍 Checking for broken internal links..."
          # Simple check for broken chapter references
          for file in book/*.html; do
            grep -o 'href="[^"]*"' "$file" | grep -v "http" | grep -v "#" | while read -r link; do
              link_file=$(echo $link | sed 's/href="//;s/"//')
              if [[ ! -f "book/$link_file" && ! -z "$link_file" ]]; then
                echo "Warning: Possible broken link in $(basename $file): $link_file"
              fi
            done
          done || true
          echo "✅ Link check complete"
      
      - name: Upload book artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: book-html
          path: book/
          retention-days: 7